- hosts: all
  become: yes
  roles:
    - role: geerlingguy.docker
    - role: nethermind_gnosis
  vars:
    - docker_install_compose: true
    - docker_compose_version: "1.26.0"
    - docker_compose_arch: x86_64
    - docker_compose_path: /usr/local/bin/docker-compose


