version: "3.7"
services:

  haproxy:
    hostname: haproxy
    container_name: haproxy
    image: haproxy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      net:
        ipv4_address: ${HAPROXY_HOST_ADDRESS}
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certbot:/usr/local/etc/certs:ro
 
  nethermind:
    hostname: nethermind
    container_name: nethermind
    image: nethermind/nethermind:latest
    restart: always
    stop_grace_period: 1m
    networks:
      net:
        ipv4_address: ${NETHERMIND_HOST_ADDRESS}
    ports:
      - "30303:30303/tcp" # p2p
      - "30303:30303/udp" # p2p
    volumes:
      - ./nethermind_db:/nethermind/nethermind_db
      - ./keystore:/nethermind/keystore
      - ${NETHERMIND_VOLUME_LOGS}:/nethermind/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_CONFIG=${NETHERMIND_CONFIG}
      - NETHERMIND_JSONRPCCONFIG_ENABLED=${NETHERMIND_JSONRPCCONFIG_ENABLED}
      - NETHERMIND_JSONRPCCONFIG_HOST=${NETHERMIND_HOST_ADDRESS}
      - NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=${NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES}
      - NETHERMIND_SYNCCONFIG_FASTSYNC=${NETHERMIND_SYNCCONFIG_FASTSYNC}
      - NETHERMIND_SYNCCONFIG_FASTBLOCKS=${NETHERMIND_SYNCCONFIG_FASTBLOCKS}
      - NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC=${NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC}
      - NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC=${NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC}

    logging:
      driver: "local"


networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "${PROJECT_SUBNET}"
