PROJECT_SUBNET=x

HAPROXY_HOST_ADDRESS=x
HAPROXY_VOLUME_CONFIG=x
HAPROXY_VOLUME_CERT=x

LETSENCRYPT_EMAIL=x
LETSENCRYPT_DOMAIN_NAME=x
LETSENCRYPT_HTTP_PORT=x
LETSENCRYPT_LOG_LEVEL=x
LETSENCRYPT_HOST_ADDRESS=x

NETHERMIND_HOST_ADDRESS=x
NETHERMIND_VOLUME_LOGS=x
NETHERMIND_CONFIG=x
NETHERMIND_JSONRPCCONFIG_ENABLED=x
NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=x
